server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categoria/**
        - id: my-service
          uri: lb://my-service
          predicates:
            - Path=/users/**
